version: 0.2


phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - echo Logging in to Amazon ECR ...
    - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
    - echo Building the Docker-compose image...
    - docker-compose build
  post_build:
    commands:
    - echo Pushing the Docker image...
    - printf '[{"name":"<name of container>","imageUri":"<path of your image"}]'   > imagedefinitions.json
    - cat imagedefinitions.json
  artifacts:
    files: imagedefinitions.json
